import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import LoginModal from "./components/modals/LoginModal";
import SignupModal from "./components/modals/SignupModal";
import AddRecipeModal from "./components/modals/AddRecipeModal";
import SearchModal from "./components/modals/SearchModal"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TadkaTales",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <div className="pt-32">
          {children}
        </div>
        <LoginModal/>
        <SignupModal/>
        <AddRecipeModal/>
        <SearchModal/>
      </body>
    </html>
  );
}
